docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - Methods: methods.md
        - Examples: examples.md
site_name: laminas-permissions-rbac
site_description: laminas-permissions-rbac
repo_url: 'https://github.com/laminas/laminas-permissions-rbac'

